---
service: lambda-middleware

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 60
  lambdaHashingVersion: '20201221'
  eventBridge:
    useCloudFormation: true

functions:
  source:
    handler: source.handler

  target:
    handler: target.handler
    events:
      - eventBridge:
          eventBus: lambda-middleware
          pattern:
            source:
              - source
            detail-type:
              - 'Lambda Invocation Status Change'

custom:
  localstack:
    stages:
      - dev
    host: http://localhost
    edgePort: 4566
